FORMAT: 1A
HOST: http://curious-api.app/

# Curious API

# Authentication [/authentication]

## OAuth [POST /authentication/client]

In order to interact with the Curious API, you must have a Client ID and Client Secret. 
Contact support about obtaining one.

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json

    + Body

            {
                "grant_type": "client_credentials",
                "client_id": "YOUR_CLIENT_ID",
                "client_secret": "YOUR_CLIENT_SECRET"
            }

+ Response 200 (application/json)

        {
            "access_token": "8vj7ZAkqrJDAMfbFWCUOaz1KFmpWASpyeODmozo3",
            "token_type": "Bearer",
            "expires_in": 3600
        }
        
## User Authentication [POST /authentication/user]

After authenticating the client with the API, you can then authenticate a user into the app.

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json

    + Body

            {
                "username": "YOUR_USERNAME",
                "password": "YOUR_PASSWORD"
            }

+ Response 200 (application/json)

# Users [/users]

## Create User [POST /users]

Register a new user.

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json

    + Body

            {
                "username": "user123",
                "password": "password123",
                "password_confirmation": "password123",
                "email": "test123@test.com",
                "invite": "123456"
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": 1,
                "username": "user123",
                "email": "test123@test.com",
                "invite_count": 5
            }
        }
    
## Get User [GET /users/{id}?include={includes}]

Retrieve information about a user.

+ Parameters

    + id (number) - ID of the User
    + includes (enum(String)) - Includes that may be attached to the user
        + Members
            + `subscribers`
            + `channels`
            + `invites`
            + `invite`

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json
            Authorization: Bearer RHD8qRvuCYHktgDce6236bpYXkrohaUTTdXX48nk

+ Response 200 (application/json)

        {
            "data": {
                "id": 1,
                "username": "user123",
                "email": "test123@test.com",
                "invite_count": 5
            }
        }

## Get Current User [GET /users/me?include={includes}]

Retrieve information about the currently authenticated user.

+ Parameters

    + includes (enum(String)) - Includes that may be attached to the user
        + Members
            + `subscribers`
            + `channels`
            + `invites`
            + `invite`

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json
            Authorization: Bearer RHD8qRvuCYHktgDce6236bpYXkrohaUTTdXX48nk

+ Response 200 (application/json)

        {
            "data": {
                "id": 1,
                "username": "user123",
                "email": "test123@test.com",
                "invite_count": 5
            }
        }
        
## Update User [PUT /users/{id}]

Update a user's information.

+ Parameters

    + id (number) - ID of the User

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json
            Authorization: Bearer RHD8qRvuCYHktgDce6236bpYXkrohaUTTdXX48nk

    + Body

            {
                "username": "user1234",
                "email": "test1234@test.com"
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": 1,
                "username": "user1234",
                "email": "test1234@test.com",
                "invite_count": 5
            }
        }
        
## Delete User [DELETE /users/{id}]

Delete a user from the app.

+ Parameters

    + id (number) - ID of the User

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json
            Authorization: Bearer RHD8qRvuCYHktgDce6236bpYXkrohaUTTdXX48nk

+ Response 200 (application/json)

## Invite User [POST /users/{id}/invites]

Invites a new user to join the app.

+ Parameters

    + id (number) - ID of the User that is inviting.

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json
            Authorization: Bearer RHD8qRvuCYHktgDce6236bpYXkrohaUTTdXX48nk

    + Body

            {
                "email": "test123@test.com"
            }

+ Response 204 (application/json)

## Subscribe To A User [POST /users/{id}/subscribers]

Subscribes the authenticated user to another.

+ Parameters

    + id (number) - ID of the User that is being subscribed to.

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json
            Authorization: Bearer RHD8qRvuCYHktgDce6236bpYXkrohaUTTdXX48nk

+ Response 204 (application/json)

## Unsubscribe From A User [DELETE /users/{id}/subscribers]

Unsubscribes the authenticated user from another.

+ Parameters

    + id (number) - ID of the User that is being unsubscribed from.

+ Request (application/json)

    + Headers

            Accept: application/vnd.curious.v1+json
            Authorization: Bearer RHD8qRvuCYHktgDce6236bpYXkrohaUTTdXX48nk

+ Response 204 (application/json)